version: "3.9"
services:
  db:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"
    ports:
      - "5100:1433"

  es:
    image: elasticsearch:7.9.1
    container_name: es
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx512m"
      discovery.type: single-node

  queue:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"

  otel-collector:
    image: otel/opentelemetry-collector:0.52.0-386
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP GRPC receiver
    depends_on:
      - jaeger
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"

  mongo1:
    image: mongo:5
    container_name: mongo1
    ports:
      - 27017:27017
    restart: always
    networks:
      - mongoCluster
    command: /usr/bin/mongod --replSet myReplicaSet --bind_ip localhost,mongo1

  mongo2:
    image: mongo:5
    container_name: mongo2
    ports:
      - 27018:27017
    networks:
      - mongoCluster
    command: /usr/bin/mongod --replSet myReplicaSet --bind_ip localhost,mongo2

  mongo3:
    image: mongo:5
    container_name: mongo3
    ports:
      - 27019:27017
    networks:
      - mongoCluster
    command: /usr/bin/mongod --replSet myReplicaSet --bind_ip localhost,mongo3

  mongoclustersetup:
    image: mongo:5
    container_name: mongoclustersetup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongoCluster
    entrypoint: [ "bash", "-c", "sleep 10 && mongosh --host mongo1:27017 --eval 'rs.initiate({
      _id: \"myReplicaSet\",
      members: [
        {_id: 0, host: \"mongo1\"},
        {_id: 1, host: \"mongo2\"},
        {_id: 2, host: \"mongo3\"}
      ]
      })'" ]

networks:
  mongoCluster:
    driver: bridge