name: Evaluate PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.sln'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker-compose up -d db queue
          dotnet test